import Head from 'next/head';
import { useRouter } from 'next/router';
// Context
import { useShopContext } from '../../lib/context';
// Query
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../../lib/queries';
// Utils
import { toCapitalize } from '../../lib/utils';
// Styled
import {
  StyledButton,
  StyledProductDetails,
  StyledProductInfo,
  StyledQuantity,
} from '../../styles/StyledProductDetails';
// Icons
import { AiFillPlusCircle, AiFillMinusCircle } from 'react-icons/ai';

export default function ProductDetails() {
  const { addProductToCart, quantity, incrementQuantity, decrementQuantity } =
    useShopContext();

  // Dynamic Routing
  const { query } = useRouter();

  const [{ data, fetching, error }] = useQuery({
    query: PRODUCT_QUERY,
    variables: { slug: query.slug },
  });

  if (fetching) return <h2>Loading...</h2>;
  if (error) return <h2>Oh no... {error.message}</h2>;

  const [product] = data.products.data;
  const { title, description, image } = product.attributes;

  return (
    <div>
      <Head>
        <title>{toCapitalize(title)} | Styled</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <StyledProductDetails>
          <img src={image.data.attributes.formats.medium.url} alt={title} />
          <StyledProductInfo>
            <h3>{toCapitalize(title)}</h3>
            <p>{toCapitalize(description)}</p>
            <StyledQuantity>
              <span>Quantity</span>
              <button onClick={decrementQuantity}>
                <AiFillMinusCircle />
              </button>
              <p>{quantity}</p>
              <button onClick={incrementQuantity}>
                <AiFillPlusCircle />
              </button>
            </StyledQuantity>
            <StyledButton
              onClick={() => addProductToCart(product.attributes, quantity)}
            >
              Add to Cart
            </StyledButton>
          </StyledProductInfo>
        </StyledProductDetails>
      </main>
    </div>
  );
}
