import Head from 'next/head';

export default function Cancel() {
  return (
    <div>
      <Head>
        <title>Cancel | Styled</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Canceled</h1>
      </main>
    </div>
  );
}
