import Head from 'next/head';
// Query
import { useQuery } from 'urql';
import { PRODUCTS_QUERY } from '../lib/queries';
// Components
import Product from '../components/Product';
// Styled
import { StyledGallery } from '../styles/StyledGallery';

export default function Home() {
  const [{ data, fetching, error }] = useQuery({ query: PRODUCTS_QUERY });

  if (fetching) return <h2>Loading...</h2>;
  if (error) return <h2>Oh no... {error.message}</h2>;

  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Styled Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <StyledGallery>
          {products.map(({ attributes }) => (
            <Product key={attributes.slug} attributes={attributes} />
          ))}
        </StyledGallery>
      </main>
    </div>
  );
}
